/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/scene.glb 
*/

import React from 'react'
import { useGLTF, Html, PerspectiveCamera } from '@react-three/drei'
import HeroPage from './HeroPage'

export function Scene(props) {
  const { nodes, materials } = useGLTF('/models/scene.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.093, 0, 0.135]} rotation={[Math.PI / 2, 0, 0.069]} scale={0.01}>
        <mesh geometry={nodes.backlit_001_mesh.geometry} material={materials.keyboard} position={[-23.917, -11.117, -0.607]} />
        <mesh geometry={nodes.backlit_002_mesh.geometry} material={materials.keyboard} position={[42.984, -11.117, -0.607]} />
        <mesh geometry={nodes.keyboard_mesh.geometry} material={materials.keyboard} />
        <mesh geometry={nodes.back_support_001_mesh.geometry} material={materials.keyboard} position={[47.869, -11.597, -0.353]} />
        <mesh geometry={nodes.back_support_002_mesh.geometry} material={materials.keyboard} position={[47.904, 11.525, -0.353]} />
        <mesh geometry={nodes.back_support_003_mesh.geometry} material={materials.keyboard} position={[-29.826, -12.814, -0.353]} />
        <mesh geometry={nodes.back_support_004_mesh.geometry} material={materials.keyboard} position={[-29.792, 11.525, -0.353]} />
        <mesh geometry={nodes.keyboard_keys_001_mesh.geometry} material={materials.keyboard} position={[-9.449, 2.602, -1.949]} />
        <mesh geometry={nodes.keyboard_keys_002_mesh.geometry} material={materials.keyboard} position={[-12.985, 2.602, -1.949]} />
        <mesh geometry={nodes.keyboard_keys_003_mesh.geometry} material={materials.keyboard} position={[-2.387, 2.602, -1.949]} />
        <mesh geometry={nodes.keyboard_keys_004_mesh.geometry} material={materials.keyboard} position={[-5.923, 2.602, -1.949]} />
        <mesh geometry={nodes.keyboard_keys_005_mesh.geometry} material={materials.keyboard} position={[1.161, 2.602, -1.949]} />
        <mesh geometry={nodes.keyboard_keys_006_mesh.geometry} material={materials.keyboard} position={[14.862, 9.911, -1.799]} />
        <mesh geometry={nodes.keyboard_keys_007_mesh.geometry} material={materials.keyboard} position={[6.436, 9.912, -1.831]} />
        <mesh geometry={nodes.keyboard_keys_008_mesh.geometry} material={materials.keyboard} position={[28.19, 6.391, -1.872]} />
        <mesh geometry={nodes.keyboard_keys_009_mesh.geometry} material={materials.keyboard} position={[39.879, 6.306, -1.874]} />
        <mesh geometry={nodes.keyboard_keys_010_mesh.geometry} material={materials.keyboard} position={[9.916, 6.242, -1.875]} />
        <mesh geometry={nodes.keyboard_keys_011_mesh.geometry} material={materials.keyboard} position={[43.369, 6.306, -1.874]} />
        <mesh geometry={nodes.keyboard_keys_012_mesh.geometry} material={materials.keyboard} position={[10.644, 9.911, -1.814]} />
        <mesh geometry={nodes.keyboard_keys_013_mesh.geometry} material={materials.keyboard} position={[-20.962, 9.911, -1.812]} />
        <mesh geometry={nodes.keyboard_keys_014_mesh.geometry} material={materials.keyboard} position={[36.418, 6.306, -1.874]} />
        <mesh geometry={nodes.keyboard_keys_015_mesh.geometry} material={materials.keyboard} position={[6.382, 6.242, -1.875]} />
        <mesh geometry={nodes.keyboard_keys_016_mesh.geometry} material={materials.keyboard} position={[-25.154, 9.911, -1.812]} />
        <mesh geometry={nodes.keyboard_keys_017_mesh.geometry} material={materials.keyboard} position={[31.636, 9.936, -1.813]} />
        <mesh geometry={nodes.keyboard_keys_018_mesh.geometry} material={materials.keyboard} position={[-29.55, -4.571, -2.097]} />
        <mesh geometry={nodes.keyboard_keys_019_mesh.geometry} material={materials.keyboard} position={[28.177, 9.936, -1.8]} />
        <mesh geometry={nodes.keyboard_keys_020_mesh.geometry} material={materials.keyboard} position={[-28.37, 2.567, -1.945]} />
        <mesh geometry={nodes.keyboard_keys_021_mesh.geometry} material={materials.keyboard} position={[-28.694, -1.001, -1.991]} />
        <mesh geometry={nodes.keyboard_keys_022_mesh.geometry} material={materials.keyboard} position={[-24.343, -1.005, -2.117]} />
        <mesh geometry={nodes.keyboard_keys_023_mesh.geometry} material={materials.keyboard} position={[24.714, 9.936, -1.803]} />
        <mesh geometry={nodes.keyboard_keys_024_mesh.geometry} material={materials.keyboard} position={[-27.653, 6.246, -1.874]} />
        <mesh geometry={nodes.keyboard_keys_025_mesh.geometry} material={materials.keyboard} position={[-29.338, 9.911, -1.812]} />
        <mesh geometry={nodes.keyboard_keys_026_mesh.geometry} material={materials.keyboard} position={[19.074, 9.911, -1.8]} />
        <mesh geometry={nodes.keyboard_keys_027_mesh.geometry} material={materials.keyboard} position={[43.369, 9.938, -1.8]} />
        <mesh geometry={nodes.keyboard_keys_028_mesh.geometry} material={materials.keyboard} position={[31.651, -9.258, -2.19]} />
        <mesh geometry={nodes.keyboard_keys_029_mesh.geometry} material={materials.keyboard} position={[-25.972, -4.57, -2.097]} />
        <mesh geometry={nodes.keyboard_keys_030_mesh.geometry} material={materials.keyboard} position={[-22.412, -4.57, -2.096]} />
        <mesh geometry={nodes.keyboard_keys_031_mesh.geometry} material={materials.keyboard} position={[-18.862, -4.572, -2.096]} />
        <mesh geometry={nodes.keyboard_keys_032_mesh.geometry} material={materials.keyboard} position={[-15.327, -4.571, -2.094]} />
        <mesh geometry={nodes.keyboard_keys_033_mesh.geometry} material={materials.keyboard} position={[-11.812, -4.571, -2.094]} />
        <mesh geometry={nodes.keyboard_keys_034_mesh.geometry} material={materials.keyboard} position={[-8.307, -4.569, -2.094]} />
        <mesh geometry={nodes.keyboard_keys_035_mesh.geometry} material={materials.keyboard} position={[-4.784, -4.572, -2.094]} />
        <mesh geometry={nodes.keyboard_keys_036_mesh.geometry} material={materials.keyboard} position={[-1.304, -4.571, -2.094]} />
        <mesh geometry={nodes.keyboard_keys_037_mesh.geometry} material={materials.keyboard} position={[2.205, -4.572, -2.094]} />
        <mesh geometry={nodes.keyboard_keys_038_mesh.geometry} material={materials.keyboard} position={[5.651, -4.571, -2.115]} />
        <mesh geometry={nodes.keyboard_keys_039_mesh.geometry} material={materials.keyboard} position={[9.117, -4.571, -2.115]} />
        <mesh geometry={nodes.keyboard_keys_040_mesh.geometry} material={materials.keyboard} position={[12.576, -4.571, -2.115]} />
        <mesh geometry={nodes.keyboard_keys_041_mesh.geometry} material={materials.keyboard} position={[-29.829, -9.224, -2.189]} />
        <mesh geometry={nodes.keyboard_keys_042_mesh.geometry} material={materials.keyboard} position={[-23.605, 2.602, -1.949]} />
        <mesh geometry={nodes.keyboard_keys_043_mesh.geometry} material={materials.keyboard} position={[-22.181, 6.243, -1.877]} />
        <mesh geometry={nodes.keyboard_keys_044_mesh.geometry} material={materials.keyboard} position={[-7.262, 9.901, -1.835]} />
        <mesh geometry={nodes.keyboard_keys_045_mesh.geometry} material={materials.keyboard} position={[46.822, 0.735, -1.986]} />
        <mesh geometry={nodes.keyboard_keys_046_mesh.geometry} material={materials.keyboard} position={[36.418, 2.665, -1.947]} />
        <mesh geometry={nodes.keyboard_keys_047_mesh.geometry} material={materials.keyboard} position={[46.822, 8.048, -1.838]} />
        <mesh geometry={nodes.keyboard_keys_048_mesh.geometry} material={materials.keyboard} position={[38.137, 9.932, -1.8]} />
        <mesh geometry={nodes.keyboard_keys_049_mesh.geometry} material={materials.keyboard} position={[16.407, 6.266, -1.871]} />
        <mesh geometry={nodes.keyboard_keys_050_mesh.geometry} material={materials.keyboard} position={[24.66, -1.108, -2.024]} />
        <mesh geometry={nodes.keyboard_keys_051_mesh.geometry} material={materials.keyboard} position={[17.734, -4.574, -2.09]} />
        <mesh geometry={nodes.keyboard_keys_052_mesh.geometry} material={materials.keyboard} position={[17.309, 0.78, -1.88]} />
        <mesh geometry={nodes.keyboard_keys_053_mesh.geometry} material={materials.keyboard} position={[-23.891, -9.184, -2.186]} />
        <mesh geometry={nodes.keyboard_keys_054_mesh.geometry} material={materials.keyboard} position={[-20.427, -9.184, -2.187]} />
        <mesh geometry={nodes.keyboard_keys_055_mesh.geometry} material={materials.keyboard} position={[2.801, 6.242, -1.875]} />
        <mesh geometry={nodes.keyboard_keys_056_mesh.geometry} material={materials.keyboard} position={[11.639, 2.602, -1.949]} />
        <mesh geometry={nodes.keyboard_keys_057_mesh.geometry} material={materials.keyboard} position={[-15.051, 6.242, -1.875]} />
        <mesh geometry={nodes.keyboard_keys_058_mesh.geometry} material={materials.keyboard} position={[39.879, 2.665, -1.947]} />
        <mesh geometry={nodes.keyboard_keys_059_mesh.geometry} material={materials.keyboard} position={[8.157, 2.602, -1.949]} />
        <mesh geometry={nodes.keyboard_keys_060_mesh.geometry} material={materials.keyboard} position={[-11.505, 6.242, -1.875]} />
        <mesh geometry={nodes.keyboard_keys_061_mesh.geometry} material={materials.keyboard} position={[-18.626, 6.242, -1.875]} />
        <mesh geometry={nodes.keyboard_keys_062_mesh.geometry} material={materials.keyboard} position={[4.664, 2.602, -1.949]} />
        <mesh geometry={nodes.keyboard_keys_063_mesh.geometry} material={materials.keyboard} position={[-0.799, 6.242, -1.875]} />
        <mesh geometry={nodes.keyboard_keys_064_mesh.geometry} material={materials.keyboard} position={[43.369, 2.665, -1.947]} />
        <mesh geometry={nodes.keyboard_keys_065_mesh.geometry} material={materials.keyboard} position={[-4.372, 6.242, -1.875]} />
        <mesh geometry={nodes.keyboard_keys_066_mesh.geometry} material={materials.keyboard} position={[-7.957, 6.242, -1.875]} />
        <mesh geometry={nodes.keyboard_keys_067_mesh.geometry} material={materials.keyboard} position={[-17.001, -9.184, -2.184]} />
        <mesh geometry={nodes.keyboard_keys_068_mesh.geometry} material={materials.keyboard} position={[-13.559, -9.184, -2.188]} />
        <mesh geometry={nodes.keyboard_keys_069_mesh.geometry} material={materials.keyboard} position={[-7.369, -9.224, -2.185]} />
        <mesh geometry={nodes.keyboard_keys_070_mesh.geometry} material={materials.keyboard} position={[-3.916, -9.224, -2.182]} />
        <mesh geometry={nodes.keyboard_keys_071_mesh.geometry} material={materials.keyboard} position={[-0.473, -9.224, -2.186]} />
        <mesh geometry={nodes.keyboard_keys_072_mesh.geometry} material={materials.keyboard} position={[2.978, -9.224, -2.186]} />
        <mesh geometry={nodes.keyboard_keys_073_mesh.geometry} material={materials.keyboard} position={[9.014, -9.242, -2.2]} />
        <mesh geometry={nodes.keyboard_keys_074_mesh.geometry} material={materials.keyboard} position={[12.49, -9.242, -2.185]} />
        <mesh geometry={nodes.keyboard_keys_075_mesh.geometry} material={materials.keyboard} position={[15.952, -9.242, -2.195]} />
        <mesh geometry={nodes.keyboard_keys_076_mesh.geometry} material={materials.keyboard} position={[19.416, -9.242, -2.18]} />
        <mesh geometry={nodes.keyboard_keys_077_mesh.geometry} material={materials.keyboard} position={[24.708, -9.257, -2.198]} />
        <mesh geometry={nodes.keyboard_keys_078_mesh.geometry} material={materials.keyboard} position={[28.153, -9.258, -2.192]} />
        <mesh geometry={nodes.keyboard_keys_079_mesh.geometry} material={materials.keyboard} position={[24.66, -4.661, -2.096]} />
        <mesh geometry={nodes.keyboard_keys_080_mesh.geometry} material={materials.keyboard} position={[28.123, -4.661, -2.091]} />
        <mesh geometry={nodes.keyboard_keys_081_mesh.geometry} material={materials.keyboard} position={[31.591, -4.661, -2.104]} />
        <mesh geometry={nodes.keyboard_keys_082_mesh.geometry} material={materials.keyboard} position={[36.418, -4.571, -2.094]} />
        <mesh geometry={nodes.keyboard_keys_083_mesh.geometry} material={materials.keyboard} position={[39.879, -4.571, -2.094]} />
        <mesh geometry={nodes.keyboard_keys_084_mesh.geometry} material={materials.keyboard} position={[43.369, -4.571, -2.094]} />
        <mesh geometry={nodes.keyboard_keys_085_mesh.geometry} material={materials.keyboard} position={[46.822, -4.571, -2.094]} />
        <mesh geometry={nodes.keyboard_keys_086_mesh.geometry} material={materials.keyboard} position={[-20.824, -1.006, -2.068]} />
        <mesh geometry={nodes.keyboard_keys_087_mesh.geometry} material={materials.keyboard} position={[-17.334, -1.007, -2.068]} />
        <mesh geometry={nodes.keyboard_keys_088_mesh.geometry} material={materials.keyboard} position={[-13.845, -1.007, -2.058]} />
        <mesh geometry={nodes.keyboard_keys_089_mesh.geometry} material={materials.keyboard} position={[-10.375, -1.007, -2.055]} />
        <mesh geometry={nodes.keyboard_keys_090_mesh.geometry} material={materials.keyboard} position={[-6.877, -1.007, -2.047]} />
        <mesh geometry={nodes.keyboard_keys_091_mesh.geometry} material={materials.keyboard} position={[-3.388, -1.007, -2.047]} />
        <mesh geometry={nodes.keyboard_keys_092_mesh.geometry} material={materials.keyboard} position={[0.109, -1.007, -2.028]} />
        <mesh geometry={nodes.keyboard_keys_093_mesh.geometry} material={materials.keyboard} position={[3.615, -1.007, -2.028]} />
        <mesh geometry={nodes.keyboard_keys_094_mesh.geometry} material={materials.keyboard} position={[7.104, -1.007, -2.028]} />
        <mesh geometry={nodes.keyboard_keys_095_mesh.geometry} material={materials.keyboard} position={[10.625, -1.009, -2.023]} />
        <mesh geometry={nodes.keyboard_keys_096_mesh.geometry} material={materials.keyboard} position={[14.138, -1.009, -2.023]} />
        <mesh geometry={nodes.keyboard_keys_097_mesh.geometry} material={materials.keyboard} position={[28.123, -1.108, -2.019]} />
        <mesh geometry={nodes.keyboard_keys_098_mesh.geometry} material={materials.keyboard} position={[31.591, -1.108, -2.031]} />
        <mesh geometry={nodes.keyboard_keys_099_mesh.geometry} material={materials.keyboard} position={[36.418, -0.969, -2.021]} />
        <mesh geometry={nodes.keyboard_keys_100_mesh.geometry} material={materials.keyboard} position={[39.879, -0.969, -2.021]} />
        <mesh geometry={nodes.keyboard_keys_101_mesh.geometry} material={materials.keyboard} position={[43.369, -0.969, -2.021]} />
        <mesh geometry={nodes.keyboard_keys_102_mesh.geometry} material={materials.keyboard} position={[-20.058, 2.602, -1.949]} />
        <mesh geometry={nodes.keyboard_keys_103_mesh.geometry} material={materials.keyboard} position={[-16.522, 2.602, -1.949]} />
      </group>
      <group position={[0.265, 0, -0.407]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <group position={[26.94, 62.442, 0]} rotation={[0, 0, 2.809]}>
          <mesh geometry={nodes.body_001_mesh.geometry} material={materials.body} position={[0, 0.059, -2.16]} />
          <mesh geometry={nodes.bottom_001_mesh.geometry} material={materials.body} position={[0, -0.479, -0.003]} />
          <mesh geometry={nodes.middle_001_mesh.geometry} material={materials.accent} position={[-0.004, 0.574, -1.419]} />
          <mesh geometry={nodes.wheel_001_mesh.geometry} material={materials.wheel} position={[0.003, 3.373, -2.64]} />
          <mesh geometry={nodes.wheel_well_001_mesh.geometry} material={materials.accent} position={[0, 2.455, -3.192]} />
        </group>
      </group>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <group position={[-53.324, -10.311, 0]} rotation={[0, 0, -0.426]}>
          <mesh geometry={nodes.base_support_002_mesh.geometry} material={materials.Screen} position={[0.001, -0.403, -0.672]} />
          <mesh geometry={nodes.speaker_001_mesh.geometry} material={materials.Screen} position={[0, 0, -0.593]} />
          <mesh geometry={nodes.wire_connector_002_mesh.geometry} material={materials.Screen} position={[0.009, -5.198, -8.067]} rotation={[0.1, 0, 0]} />
          <mesh geometry={nodes.woofer_002_mesh.geometry} material={materials.Screen} position={[0.001, 3.187, -12.841]} />
        </group>
        <group position={[47.735, -9.41, 0]} rotation={[0, 0, 0.423]}>
          <mesh geometry={nodes.base_support_001_mesh.geometry} material={materials.Screen} position={[0.136, -0.848, -0.666]} />
          <mesh geometry={nodes.coil_001_mesh.geometry} material={materials.Screen} position={[-4.639, 6.055, -21.391]} />
          <mesh geometry={nodes.coil_002_mesh.geometry} material={materials.Screen} position={[-1.283, 6.055, -21.391]} />
          <mesh geometry={nodes.speaker_002_mesh.geometry} material={materials.Screen} position={[0, -0.445, -0.528]} />
          <mesh geometry={nodes.volume_001_mesh.geometry} material={materials.Screen} position={[3.054, 2.401, -21.409]} rotation={[0, 0, -1.553]} />
          <mesh geometry={nodes.wire_connector_001_mesh.geometry} material={materials.Screen} position={[0.04, -5.643, -8.067]} rotation={[0.1, 0, 0]} />
          <mesh geometry={nodes.woofer_003_mesh.geometry} material={materials.Screen} position={[0.078, 2.743, -12.841]} />
        </group>
      </group>
      <group position={[0, 0, -0.597]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh geometry={nodes.pen_mesh001.geometry} material={materials['pen.001']} position={[-31.492, 88.39, 0]} rotation={[Math.PI / 2, 0.854, -Math.PI / 2]} />
        <mesh geometry={nodes.tip_mesh.geometry} material={materials['pen.001']} />
      </group>
      <group position={[-0.196, 0, 0.462]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <group position={[99.659, -39.824, 0]} rotation={[0, 0, 0.16]}>
          <mesh geometry={nodes.binding_001_mesh.geometry} material={materials.binding} position={[0.111, 0, -2.059]} />
          <mesh geometry={nodes.cover_001_mesh.geometry} material={materials.cover} position={[0, 0, -2.058]} />
          <mesh geometry={nodes.page_001_mesh.geometry} material={materials.page} position={[0.112, 0, -2.06]} />
          <mesh geometry={nodes.seal_001_mesh.geometry} material={materials.seal} position={[-10.103, 0, -2.058]} />
        </group>
        <group position={[-51.849, -26.226, 0]} rotation={[0, 0, -0.324]}>
          <mesh geometry={nodes.binding_002_mesh.geometry} material={materials.binding} position={[0, 0, -1.043]} />
          <mesh geometry={nodes.cover_002_mesh.geometry} material={materials.cover} position={[0, 0, -0.519]} />
          <mesh geometry={nodes.page_002_mesh.geometry} material={materials.page} position={[10.886, 0, -2.167]} />
          <mesh geometry={nodes.page_003_mesh.geometry} material={materials.page} position={[0.29, 0, -1.742]} />
          <mesh geometry={nodes.page_004_mesh.geometry} material={materials.page} position={[0.29, 0, -1.742]} />
          <mesh geometry={nodes.page_005_mesh.geometry} material={materials.page} position={[-11.017, 0, -1.8]} />
          <mesh geometry={nodes.page_006_mesh.geometry} material={materials.page} position={[-9.671, 0, -2.984]} />
          <mesh geometry={nodes.page_007_mesh.geometry} material={materials.page} position={[0.29, 0, -1.742]} />
          <mesh geometry={nodes.page_008_mesh.geometry} material={materials.page} position={[11.243, 0, -1.456]} />
          <mesh geometry={nodes.seal_002_mesh.geometry} material={materials.seal} position={[-0.005, 0, -1.278]} />
        </group>
      </group>
      <group position={[0, 0, -0.14]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh geometry={nodes.back_connector_001_mesh.geometry} material={materials.Screen} position={[1.359, -4.471, -26.905]} />
        <mesh geometry={nodes.back_connector_002_mesh.geometry} material={materials.Screen} position={[-1.372, -4.471, -26.895]} />
        <mesh geometry={nodes.back_holder_001_mesh.geometry} material={materials.Screen} position={[2.918, 0.522, -32.941]} />
        <mesh geometry={nodes.back_holder_002_mesh.geometry} material={materials.Screen} position={[-2.918, 0.522, -32.941]} />
        <mesh geometry={nodes.back_plate_mesh.geometry} material={materials.Screen} position={[0, 0.986, -32.853]} />
        <mesh geometry={nodes.base_mesh.geometry} material={materials.Screen} position={[0, -1.569, -0.75]} />
        <mesh geometry={nodes.power_button_mesh.geometry} material={materials.Screen} position={[29.023, 5.673, -16.478]} />
        <mesh geometry={nodes.power_plate_mesh.geometry} material={materials.Screen} position={[0, -8.987, -2.684]} />
        <mesh geometry={nodes.power_port_mesh.geometry} material={materials.Screen} position={[0, -9.434, -2.684]} />
        <mesh geometry={nodes.screen_mesh.geometry} material={materials.Screen} position={[0, 2.61, -33.014]} rotation={[-0.117, 0, 0]} />
        <mesh geometry={nodes.screen_windows.geometry} material={materials.screen} position={[0, 2.61, -33.014]} rotation={[-0.117, 0, 0]}>
                {/* This is where the HTML screen goes */}
                <Html
                  transform
                  occlude
                  position={[0, 1, -1.6]}         // tweak to match the plane depth
                  rotation={[Math.PI / 2, Math.PI, Math.PI]}    // tweak until it’s flush with screen
                  scale = {[1, 1, 1]}
                >
                  <div className="screen-wrapper" onPointerDown={(e) => e.stopPropagation()}
                    style={{
                      borderRadius: '20px',        // rounded corners
                      overflow: 'hidden',          // important so content stays inside corners
                      boxShadow: '0 0 10px rgba(0,0,0,0.3)', // optional shadow for depth
                    }}
                    >
                    <HeroPage />
                  </div>
                </Html>
              </mesh>
        <mesh geometry={nodes.support_mesh.geometry} material={materials.Screen} position={[0, -8.184, 0.26]} rotation={[0.15, 0, 0]} />
        <mesh geometry={nodes.usb_port_001_mesh.geometry} material={materials.Screen} position={[0, -9.091, -5.973]} />
        <mesh geometry={nodes.usb_port_002_mesh.geometry} material={materials.Screen} position={[0, -9.158, -4.973]} />
        <mesh geometry={nodes.usb_port_003_mesh.geometry} material={materials.Screen} position={[0, -9.251, -3.973]} />
      </group>
      <group position={[-0.787, 0, -0.109]} rotation={[Math.PI / 2, 0, -0.81]} scale={0.01}>
        <group position={[0, -0.036, -1.049]}>
          <group position={[0, -8.114, -19.134]}>
            <group position={[0, 15.914, -21.565]}>
              <mesh geometry={nodes.office_lamp_03_bulb_001_mesh.geometry} material={materials.office_lamp} position={[-2.003, -0.001, -0.001]} />
              <mesh geometry={nodes.office_lamp_03_bulb_002_mesh.geometry} material={materials.Screen} position={[-5.301, -0.001, -0.009]} />
              <mesh geometry={nodes.office_lamp_03_hinge_mesh.geometry} material={materials.Screen} />
              <mesh geometry={nodes.office_lamp_03_shade_mesh.geometry} material={materials.Shade} position={[0, -0.001, -0.162]} />
            </group>
            <mesh geometry={nodes.office_lamp_03_stand_005_mesh.geometry} material={materials.Screen} />
            <mesh geometry={nodes.office_lamp_03_stand_006_mesh.geometry} material={materials.Screen} position={[0, 6.102, -7.974]} />
            <mesh geometry={nodes.office_lamp_03_stud_003_mesh.geometry} material={materials.Screen} position={[0, 0.848, -0.181]} />
            <mesh geometry={nodes.office_lamp_03_stud_004_mesh.geometry} material={materials.Screen} position={[0, 1.237, -1.357]} />
          </group>
          <mesh geometry={nodes.office_lamp_03_stand_001_mesh.geometry} material={materials.Screen} position={[0, 0.205, -0.689]} />
          <mesh geometry={nodes.office_lamp_03_stand_002_mesh.geometry} material={materials.Screen} position={[0, 0, -0.215]} />
          <mesh geometry={nodes.office_lamp_03_stand_003_mesh.geometry} material={materials.Screen} position={[0, -0.038, -0.341]} />
          <mesh geometry={nodes.office_lamp_03_stand_004_mesh.geometry} material={materials.Screen} position={[0, -7.732, -18.586]} />
          <mesh geometry={nodes.office_lamp_03_stand_007_mesh.geometry} material={materials.Screen} position={[0, -7.732, -18.586]} />
          <mesh geometry={nodes.office_lamp_03_stud_001_mesh.geometry} material={materials.Screen} position={[0, -0.802, -1.1]} />
          <mesh geometry={nodes.office_lamp_03_stud_002_mesh.geometry} material={materials.Screen} position={[0, -7.266, -17.925]} />
        </group>
        <mesh geometry={nodes.office_lamp_03_base_mesh.geometry} material={materials.Screen} position={[0, -0.046, -0.479]} />
        <mesh geometry={nodes.office_lamp_03_padding_001_mesh.geometry} material={materials.Screen} position={[-6.71, -0.056, -0.17]} />
        <mesh geometry={nodes.office_lamp_03_padding_002_mesh.geometry} material={materials.Screen} position={[3.355, 5.755, -0.17]} />
        <mesh geometry={nodes.office_lamp_03_padding_003_mesh.geometry} material={materials.Screen} position={[3.355, -5.867, -0.17]} />
      </group>
      <group position={[0.821, 0, -0.179]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <group position={[-0.471, -2.898, -14.142]}>
          <mesh geometry={nodes.branch_008_mesh.geometry} material={materials.branch} position={[0.042, -0.013, 0]} />
          <mesh geometry={nodes.leaf_077_mesh.geometry} material={materials.leaf} position={[-2.463, -4.277, -24.14]} />
          <mesh geometry={nodes.leaf_078_mesh.geometry} material={materials.leaf} position={[-3.176, -5.245, -25.032]} />
          <mesh geometry={nodes.leaf_079_mesh.geometry} material={materials.leaf} position={[-2.637, -4.293, -24.103]} />
          <mesh geometry={nodes.leaf_080_mesh.geometry} material={materials.leaf} position={[-3.183, -5.172, -24.927]} />
          <mesh geometry={nodes.leaf_081_mesh.geometry} material={materials.leaf} position={[-1.851, -3.463, -22.997]} />
          <mesh geometry={nodes.leaf_082_mesh.geometry} material={materials.leaf} position={[-1.971, -3.399, -22.979]} />
        </group>
        <group position={[0.155, -0.4, -14.188]}>
          <mesh geometry={nodes.branch_002_mesh.geometry} material={materials.branch} position={[0.03, -0.025, 0.033]} />
          <mesh geometry={nodes.leaf_015_mesh.geometry} material={materials.leaf} position={[-8.712, -7.358, -36.368]} />
          <mesh geometry={nodes.leaf_016_mesh.geometry} material={materials.leaf} position={[-10.267, -8.722, -38.128]} />
          <mesh geometry={nodes.leaf_017_mesh.geometry} material={materials.leaf} position={[-11.904, -9.888, -39.816]} />
          <mesh geometry={nodes.leaf_018_mesh.geometry} material={materials.leaf} position={[-7.79, -6.513, -34.942]} />
          <mesh geometry={nodes.leaf_019_mesh.geometry} material={materials.leaf} position={[-8.881, -7.33, -36.32]} />
          <mesh geometry={nodes.leaf_020_mesh.geometry} material={materials.leaf} position={[-10.495, -8.606, -38.109]} />
          <mesh geometry={nodes.leaf_021_mesh.geometry} material={materials.leaf} position={[-11.728, -9.566, -39.501]} />
          <mesh geometry={nodes.leaf_060_mesh.geometry} material={materials.leaf} position={[-7.286, -6.319, -34.715]} />
        </group>
        <group position={[2.035, -0.197, -14.156]}>
          <mesh geometry={nodes.branch_006_mesh.geometry} material={materials.branch} position={[-0.031, 0.011, 0]} />
          <mesh geometry={nodes.leaf_061_mesh.geometry} material={materials.leaf} position={[4.043, -6.455, -40.217]} />
          <mesh geometry={nodes.leaf_062_mesh.geometry} material={materials.leaf} position={[5.144, -8.261, -42.347]} />
          <mesh geometry={nodes.leaf_063_mesh.geometry} material={materials.leaf} position={[6.152, -9.89, -44.073]} />
          <mesh geometry={nodes.leaf_064_mesh.geometry} material={materials.leaf} position={[3.197, -5.468, -38.49]} />
          <mesh geometry={nodes.leaf_065_mesh.geometry} material={materials.leaf} position={[3.926, -6.595, -40.186]} />
          <mesh geometry={nodes.leaf_066_mesh.geometry} material={materials.leaf} position={[5.008, -8.324, -42.427]} />
          <mesh geometry={nodes.leaf_067_mesh.geometry} material={materials.leaf} position={[5.858, -9.61, -43.783]} />
          <mesh geometry={nodes.leaf_068_mesh.geometry} material={materials.leaf} position={[3.278, -5.354, -38.576]} />
        </group>
        <group position={[-1.021, 1.146, -14.159]}>
          <mesh geometry={nodes.branch_005_mesh.geometry} material={materials.branch} />
          <mesh geometry={nodes.leaf_046_mesh.geometry} material={materials.leaf} position={[-1.566, 5.758, -46.413]} />
          <mesh geometry={nodes.leaf_047_mesh.geometry} material={materials.leaf} position={[-1.586, 5.728, -46.121]} />
          <mesh geometry={nodes.leaf_048_mesh.geometry} material={materials.leaf} position={[-1.999, 6.816, -48.457]} />
          <mesh geometry={nodes.leaf_049_mesh.geometry} material={materials.leaf} position={[-1.792, 6.905, -48.28]} />
          <mesh geometry={nodes.leaf_050_mesh.geometry} material={materials.leaf} position={[-2.364, 8.657, -50.706]} />
          <mesh geometry={nodes.leaf_051_mesh.geometry} material={materials.leaf} position={[-2.275, 8.604, -50.266]} />
          <mesh geometry={nodes.leaf_052_mesh.geometry} material={materials.leaf} position={[-2.946, 10.38, -52.494]} />
          <mesh geometry={nodes.leaf_053_mesh.geometry} material={materials.leaf} position={[-3.59, 12.891, -54.557]} />
          <mesh geometry={nodes.leaf_054_mesh.geometry} material={materials.leaf} position={[-4.292, 15.19, -56.509]} />
          <mesh geometry={nodes.leaf_055_mesh.geometry} material={materials.leaf} position={[-5.078, 17.836, -58.097]} />
          <mesh geometry={nodes.leaf_056_mesh.geometry} material={materials.leaf} position={[-4.879, 17.76, -57.996]} />
          <mesh geometry={nodes.leaf_057_mesh.geometry} material={materials.leaf} position={[-4.225, 15.467, -56.256]} />
          <mesh geometry={nodes.leaf_058_mesh.geometry} material={materials.leaf} position={[-3.505, 12.985, -54.486]} />
          <mesh geometry={nodes.leaf_059_mesh.geometry} material={materials.leaf} position={[-2.777, 10.478, -52.377]} />
        </group>
        <group position={[-0.326, -2.351, -14.159]}>
          <mesh geometry={nodes.branch_004_mesh.geometry} material={materials.branch} />
          <mesh geometry={nodes.leaf_029_mesh.geometry} material={materials.leaf} position={[1.529, -6.557, -57.73]} />
          <mesh geometry={nodes.leaf_031_mesh.geometry} material={materials.leaf} position={[1.272, -6.717, -57.397]} />
          <mesh geometry={nodes.leaf_032_mesh.geometry} material={materials.leaf} position={[1.726, -8.507, -60.106]} />
          <mesh geometry={nodes.leaf_033_mesh.geometry} material={materials.leaf} position={[1.289, -8.277, -59.922]} />
          <mesh geometry={nodes.leaf_034_mesh.geometry} material={materials.leaf} position={[2.285, -10.745, -62.916]} />
          <mesh geometry={nodes.leaf_035_mesh.geometry} material={materials.leaf} position={[2.138, -10.428, -62.431]} />
          <mesh geometry={nodes.leaf_036_mesh.geometry} material={materials.leaf} position={[2.923, -13.147, -65.278]} />
          <mesh geometry={nodes.leaf_037_mesh.geometry} material={materials.leaf} position={[3.57, -16.328, -67.225]} />
          <mesh geometry={nodes.leaf_038_mesh.geometry} material={materials.leaf} position={[4.298, -19.585, -68.971]} />
          <mesh geometry={nodes.leaf_039_mesh.geometry} material={materials.leaf} position={[5.105, -23.215, -70.614]} />
          <mesh geometry={nodes.leaf_040_mesh.geometry} material={materials.leaf} position={[4.859, -23.082, -70.53]} />
          <mesh geometry={nodes.leaf_041_mesh.geometry} material={materials.leaf} position={[4.135, -19.883, -68.798]} />
          <mesh geometry={nodes.leaf_042_mesh.geometry} material={materials.leaf} position={[3.395, -16.451, -67.074]} />
          <mesh geometry={nodes.leaf_043_mesh.geometry} material={materials.leaf} position={[2.585, -13.03, -64.971]} />
          <mesh geometry={nodes.leaf_044_mesh.geometry} material={materials.leaf} position={[0.799, -5.007, -54.126]} />
          <mesh geometry={nodes.leaf_045_mesh.geometry} material={materials.leaf} position={[0.829, -5.044, -54.243]} />
        </group>
        <group position={[0.393, -0.016, -14.188]}>
          <mesh geometry={nodes.branch_001_mesh.geometry} material={materials.branch} />
          <mesh geometry={nodes.leaf_001_mesh.geometry} material={materials.leaf} position={[6.055, -0.951, -69.553]} />
          <mesh geometry={nodes.leaf_002_mesh.geometry} material={materials.leaf} position={[5.852, -0.928, -69.301]} />
          <mesh geometry={nodes.leaf_003_mesh.geometry} material={materials.leaf} position={[7.654, -1.115, -72.401]} />
          <mesh geometry={nodes.leaf_004_mesh.geometry} material={materials.leaf} position={[7.371, -1.395, -72.134]} />
          <mesh geometry={nodes.leaf_005_mesh.geometry} material={materials.leaf} position={[10.222, -1.494, -75.218]} />
          <mesh geometry={nodes.leaf_006_mesh.geometry} material={materials.leaf} position={[9.613, -1.609, -74.902]} />
          <mesh geometry={nodes.leaf_007_mesh.geometry} material={materials.leaf} position={[12.477, -1.813, -77.464]} />
          <mesh geometry={nodes.leaf_008_mesh.geometry} material={materials.leaf} position={[15.646, -2.41, -79.83]} />
          <mesh geometry={nodes.leaf_009_mesh.geometry} material={materials.leaf} position={[18.786, -3, -81.693]} />
          <mesh geometry={nodes.leaf_010_mesh.geometry} material={materials.leaf} position={[22.095, -3.793, -83.51]} />
          <mesh geometry={nodes.leaf_011_mesh.geometry} material={materials.leaf} position={[22.307, -3.618, -83.606]} />
          <mesh geometry={nodes.leaf_012_mesh.geometry} material={materials.leaf} position={[18.979, -3.204, -81.81]} />
          <mesh geometry={nodes.leaf_013_mesh.geometry} material={materials.leaf} position={[15.62, -2.699, -79.834]} />
          <mesh geometry={nodes.leaf_014_mesh.geometry} material={materials.leaf} position={[12.257, -2.239, -77.377]} />
          <mesh geometry={nodes.leaf_028_mesh.geometry} material={materials.leaf} position={[4.333, -0.894, -65.632]} />
          <mesh geometry={nodes.leaf_030_mesh.geometry} material={materials.leaf} position={[4.218, -0.924, -65.387]} />
        </group>
        <group position={[2.087, -0.734, -14.182]}>
          <mesh geometry={nodes.branch_009_mesh.geometry} material={materials.branch} position={[0.071, -0.024, 0]} />
          <mesh geometry={nodes.leaf_083_mesh.geometry} material={materials.leaf} position={[2.431, -1.356, -12.378]} />
          <mesh geometry={nodes.leaf_084_mesh.geometry} material={materials.leaf} position={[2.941, -2.159, -12.991]} />
          <mesh geometry={nodes.leaf_085_mesh.geometry} material={materials.leaf} position={[2.397, -1.441, -12.339]} />
          <mesh geometry={nodes.leaf_086_mesh.geometry} material={materials.leaf} position={[2.854, -2.207, -12.891]} />
        </group>
        <group position={[0.201, 0.669, -14.182]}>
          <mesh geometry={nodes.branch_003_mesh.geometry} material={materials.branch} position={[0.033, -0.116, 0]} />
          <mesh geometry={nodes.leaf_022_mesh.geometry} material={materials.leaf} position={[-0.915, 5.161, -18.373]} />
          <mesh geometry={nodes.leaf_023_mesh.geometry} material={materials.leaf} position={[-1.103, 6.152, -18.884]} />
          <mesh geometry={nodes.leaf_024_mesh.geometry} material={materials.leaf} position={[-0.753, 5.186, -18.288]} />
          <mesh geometry={nodes.leaf_025_mesh.geometry} material={materials.leaf} position={[-0.682, 4.057, -17.671]} />
          <mesh geometry={nodes.leaf_026_mesh.geometry} material={materials.leaf} position={[-0.585, 4.152, -17.654]} />
          <mesh geometry={nodes.leaf_027_mesh.geometry} material={materials.leaf} position={[-0.919, 6.189, -18.889]} />
        </group>
        <group position={[2.099, 0.578, -14.126]}>
          <mesh geometry={nodes.branch_007_mesh.geometry} material={materials.branch} position={[-0.078, -0.278, 0]} />
          <mesh geometry={nodes.leaf_069_mesh.geometry} material={materials.leaf} position={[3.092, 5.714, -28.855]} />
          <mesh geometry={nodes.leaf_070_mesh.geometry} material={materials.leaf} position={[3.808, 6.742, -31.149]} />
          <mesh geometry={nodes.leaf_071_mesh.geometry} material={materials.leaf} position={[4.733, 7.83, -33.547]} />
          <mesh geometry={nodes.leaf_072_mesh.geometry} material={materials.leaf} position={[2.51, 4.744, -27.17]} />
          <mesh geometry={nodes.leaf_073_mesh.geometry} material={materials.leaf} position={[3.163, 5.56, -29.113]} />
          <mesh geometry={nodes.leaf_074_mesh.geometry} material={materials.leaf} position={[3.989, 6.663, -31.468]} />
          <mesh geometry={nodes.leaf_075_mesh.geometry} material={materials.leaf} position={[4.584, 7.584, -33.403]} />
          <mesh geometry={nodes.leaf_076_mesh.geometry} material={materials.leaf} position={[2.422, 4.886, -26.858]} />
        </group>
        <mesh geometry={nodes.dirt_mesh.geometry} material={materials.dirt} position={[0, 0, -11.237]} />
        <mesh geometry={nodes.vase_mesh.geometry} material={materials.vase} position={[0, 0, -0.049]} />
      </group>
      <PerspectiveCamera makeDefault={false} far={100} near={0.01} fov={22.895} position={[-0.607, 0.923, 0.751]} rotation={[-1.033, 0.11, 0.182]} />
      <PerspectiveCamera makeDefault={false} far={1000} near={0.01} fov={22.895} position={[0, 0.33, 0.967]} />
      <PerspectiveCamera makeDefault={false} far={1000} near={0.01} fov={22.895} position={[-0.468, -0.201, 2.848]} rotation={[0.147, 0.076, -0.011]} />
      <PerspectiveCamera makeDefault={false} far={1000} near={0.01} fov={22.458} position={[-2.668, -0.233, -0.428]} rotation={[3.085, -1.193, 3.089]} scale={0.288} />
      <group position={[0, -0.168, 0.055]} rotation={[Math.PI / 2, 0, 0]} scale={0.03}>
        <mesh geometry={nodes.Desk4_1.geometry} material={materials.wire_012012012} />
        <mesh geometry={nodes.Desk4_2.geometry} material={materials.wire_115115115} />
        <mesh geometry={nodes.Desk4_3.geometry} material={materials.wire_200200200} />
        <mesh geometry={nodes.Desk4_4.geometry} material={materials.wire_000000000} />
        <mesh geometry={nodes.Desk4_5.geometry} material={materials['01___Default']} />
        <mesh geometry={nodes.Desk4_6.geometry} material={materials.wire_088144225} />
        <mesh geometry={nodes.Desk4_7.geometry} material={materials.wire_086086086} />
        <mesh geometry={nodes.Desk4_8.geometry} material={materials.wire_153228153} />
        <mesh geometry={nodes.Desk4_9.geometry} material={materials['03___Default']} />
      </group>
      <mesh geometry={nodes.Plane.geometry} material={nodes.Plane.material} position={[0.039, -0.742, -0.119]} scale={4.141} />
      <mesh geometry={nodes.Plane001.geometry} material={nodes.Plane001.material} position={[0.039, -0.742, -0.386]} rotation={[Math.PI / 2, 0, 0]} scale={4.141} />
      <group position={[0.715, 0.152, 0.992]} rotation={[Math.PI, -0.827, Math.PI]} scale={0.288}>
        <mesh geometry={nodes.Plane003_1.geometry} material={materials.Material} />
        <mesh geometry={nodes.Plane003_2.geometry} material={materials['Material.002']} />
      </group>
      <group position={[0.529, -0.251, 0.822]} rotation={[Math.PI, -0.827, Math.PI]} scale={0.24}>
        <mesh geometry={nodes.Plane004_1.geometry} material={materials.Material} />
        <mesh geometry={nodes.Plane004_2.geometry} material={materials['Material.002']} />
      </group>
      <mesh geometry={nodes.Plane004.geometry} material={materials.Material} position={[0.467, -0.422, 0.765]} rotation={[Math.PI, -0.827, Math.PI]} scale={[0.054, 0.03, 0.167]} />
      <mesh geometry={nodes.Circle.geometry} material={materials['Material.003']} position={[0.467, -0.422, 0.765]} rotation={[Math.PI, -0.827, Math.PI]} scale={0.029} />
      <mesh geometry={nodes.Circle001.geometry} material={materials['Material.003']} position={[0.467, -0.413, 0.765]} rotation={[Math.PI, -0.827, Math.PI]} scale={[0.025, 0.065, 0.025]} />
      <mesh geometry={nodes.Plane005.geometry} material={materials['Material.003']} position={[0.469, -0.659, 0.766]} rotation={[-Math.PI, 0.744, -Math.PI]} scale={[0.024, 0.024, 0.016]} />
      <mesh geometry={nodes.Circle002.geometry} material={materials['Material.003']} position={[0.237, -0.712, 0.556]} rotation={[Math.PI, -0.827, Math.PI / 2]} scale={-0.026} />
      <mesh geometry={nodes.Circle003.geometry} material={materials['Material.003']} position={[0.192, -0.712, 0.912]} rotation={[0, -1.093, -Math.PI / 2]} scale={-0.026} />
      <mesh geometry={nodes.Circle004.geometry} material={materials['Material.003']} position={[0.511, -0.712, 1.076]} rotation={[0, 0.129, -Math.PI / 2]} scale={-0.026} />
      <mesh geometry={nodes.Circle005.geometry} material={materials['Material.003']} position={[0.781, -0.712, 0.778]} rotation={[0, 1.525, -1.571]} scale={-0.026} />
      <mesh geometry={nodes.Circle006.geometry} material={materials['Material.003']} position={[0.587, -0.712, 0.477]} rotation={[-Math.PI, 0.395, Math.PI / 2]} scale={-0.026} />
      <mesh geometry={nodes.Plane006.geometry} material={materials.Material} position={[0.467, -0.468, 0.765]} rotation={[Math.PI, -0.827, Math.PI]} scale={0.104} />
      <mesh geometry={nodes.Plane007.geometry} material={materials['Material.003']} position={[0.626, -0.539, 0.49]} rotation={[-Math.PI, -0.827, -2.937]} scale={0.036} />
      <mesh geometry={nodes.aseito_logo.geometry} material={materials['aseito logo']} position={[0.699, 0.212, 0.978]} rotation={[Math.PI / 2, 0, 2.315]} scale={0.018} />
    </group>
  )
}

useGLTF.preload('/models/scene.glb')
